language: c
compiler:
  - gcc
  - clang
env:
  - CFLAGS="-m32"
  - CFLAGS="-m64"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib
script:
  - perl --version
  - make test
  - make clean
  - make debug
  - make test 2> /dev/null >/dev/null
