sudo: false
language: c
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - gcc-multilib
env:
  - CFLAGS="-m32"
  - CFLAGS="-m64"
script:
  - perl --version
  - make test
  - make clean
  - make debug
  - make test
